services:
  db-migrator:
    image: node:20
    container_name: prod_db_migrator
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${RDS_ENDPOINT}:5432/${POSTGRES_DB}?schema=public&sslmode=require"
    volumes:
      - ./schema.prisma:/schema.prisma
    command: sh -c "npx prisma@5 db push --schema=/schema.prisma --accept-data-loss --skip-generate"
    networks:
      - internal_network
    profiles:
      - setup

  backend:
    image: ${DOCKER_USERNAME}/assetflow-api:latest
    container_name: prod_backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${RDS_ENDPOINT}:5432/${POSTGRES_DB}?schema=public&sslmode=require"
      PORT: 8080
      GIN_MODE: release
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY_HOURS: ${JWT_EXPIRY_HOURS}
      CORS_ORIGIN: ${CORS_ORIGIN}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
      BCRYPT_COST: ${BCRYPT_COST}
    volumes:
      - prod_uploads:/app/uploads
    networks:
      - internal_network

  frontend:
    image: ${DOCKER_USERNAME}/assetflow-web:latest
    container_name: prod_frontend
    restart: always
    ports:
      - "80:8080" # Map cổng 80 công khai của EC2 vào cổng 8080 của Nginx unprivileged
    depends_on:
      - backend
    networks:
      - internal_network

volumes:
  prod_uploads:

networks:
  internal_network:
    driver: bridge